# Generated by Django 4.2.2 on 2023-06-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculomodels',
            name='categoria',
            field=models.CharField(choices=[('particular', 'Particular'), ('transporte', 'Transporte'), ('carga', 'Carga')], max_length=20),
        ),
    ]
