# Generated by Django 4.2.2 on 2023-06-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculomodels_categoria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculomodels',
            options={'ordering': ['-fecha_creacion'], 'permissions': (('visualizar_catalogo', 'Visualizar Catálogo'),), 'verbose_name': 'vehículo', 'verbose_name_plural': 'vehículos'},
        ),
        migrations.AddField(
            model_name='vehiculomodels',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='vehiculomodels',
            name='marca',
            field=models.CharField(choices=[('chevrolet', 'Chevrolet'), ('fiat', 'Fiat'), ('ford', 'Ford'), ('toyota', 'Toyota')], max_length=20),
        ),
    ]
