# Generated by Django 4.0.5 on 2023-06-30 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0003_alter_vehiculomodels_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehiculoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(choices=[('Chevrolet', 'Chevrolet'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Toyota', 'Toyota')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('serial_carroceria', models.CharField(max_length=50)),
                ('serial_motor', models.CharField(max_length=50)),
                ('categoria', models.CharField(choices=[('Particular', 'Particular'), ('Transporte', 'Transporte'), ('Carga', 'Carga')], max_length=20)),
                ('precio', models.IntegerField()),
                ('clasificacion', models.CharField(blank=True, max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'ordering': ['-fecha_creacion'],
                'permissions': (('visualizar_catalogo', 'Visualizar Catálogo'),),
            },
        ),
        migrations.DeleteModel(
            name='VehiculoModels',
        ),
    ]
