# Generated by Django 4.0.5 on 2023-07-14 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0004_vehiculomodel_delete_vehiculomodels'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculomodel',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='vehiculos/'),
        ),
    ]
