# Generated by Django 4.0.5 on 2023-07-20 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0006_alter_vehiculomodel_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('Azul', 'Azul'), ('Rojo', 'Rojo'), ('Verde', 'Verde')], max_length=20)),
                ('color1', models.CharField(max_length=30)),
                ('color2', models.CharField(max_length=30)),
                ('color3', models.CharField(max_length=30)),
                ('color4', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'color',
                'verbose_name_plural': 'colores',
                'ordering': ['-color'],
            },
        ),
    ]
