# Generated by Django 4.0.5 on 2023-07-20 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0009_colormodel_color5_alter_colormodel_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='color6',
            field=models.CharField(default='#20202020', max_length=30),
        ),
    ]
